### PR TITLE
Fix picks plot when location ID is none in pick's WaveformstreamID

### PR DESCRIPTION
**Pull request by ChrisBail**
When reading from a QuakeML the picks can be associated to a` None` location ID. Picks where not found and not plotted because for each stream the program was looking for a pick with location code `''` and not `None`

Another issue was when getting `arrival.time_residual`. Now, if `None` `time_residual `is set to `0`.

### CODE REVIEW

**Comment by megies** [comment]
Can you attach a QuakeML file that illustrates the problem?

**Comment by ChrisBail** [comment]
Here is my QuakeML (it has multiple events in it)
[201501.xml.tar.gz](https://github.com/megies/obspyck/files/865504/201501.xml.tar.gz)

**Comment by megies** [comment]
Hmm.. in your QuakeML file the SEED ID of the picks is not fully specified, it lacks location and channel code which obspyck probably expects to be set..

```xml
      <pick publicID="smi:local/9ab52b03-0bfb-4379-aecc-05c370bf98b0">
        <time>
          <value>2015-01-22T00:00:27.961000Z</value>
        </time>
        <waveformID networkCode="OO" stationCode="AXCC1"></waveformID>
        <methodID>smi:local/K</methodID>
        <phaseHint>P</phaseHint>
        <evaluationMode>automatic</evaluationMode>
      </pick>
```

**Comment by megies** [comment]
This branch was a bit messy, so I implemented it quickly in a clean way in #51. As mentioned there it won't be possible to modify/delete those picks yet..

**Comment by megies** [comment]
> Another issue was when getting arrival.time_residual. Now, if None time_residualis set to 0.

Do you also have an example file with an Arrival without time residual set?

**Comment by ChrisBail** [comment]
The previous file I gave you has arrivals with no time residuals set.

**Comment by megies** [comment]
Ah, overlooked them.. I'm tending to just ignore those stub arrivals..

**Comment by megies** [comment]
@ChrisBail, see #52

**Pull request closed without merging**
